apiVersion: v1
kind: ConfigMap
metadata:
  name: alurafood-order-postgres-configmap
  labels:
    app: alurafood-order-postgres-configmap
data:
  POSTGRES_DB: alurafood-order
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword