apiVersion: v1
kind: Pod
metadata:
  name: discovery-pod
  labels:
    app: discovery-pod
spec:
  containers:
    - name: discovery-pod-container
      image: docker.io/library/discovery-pod
      #      image: docker.io/library/openjdk
      ports:
        - containerPort: 8761
      imagePullPolicy: Never