apiVersion: v1
kind: Service
metadata:
  name: order-loadbalancer
  labels:
    app: order-loadbalancer
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      nodePort: 30333
  externalTrafficPolicy: Local
  selector:
    app: order-pod