apiVersion: v1
kind: Service
metadata:
  name: order-loadbalancer
  labels:
    app: nginx
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: order-pod