apiVersion: v1
kind: Service
metadata:
  name: postgres-payment-nodeport # Sets service name
  labels:
    app: postgres-payment-nodeport # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
      nodePort: 31976
  selector:
    app: alurafood-payment-postgres